### ISSUE TITLE
Simulation Code Availability

### ISSUE THREAD

**Issue by DOH-PNT0303** [KleistLab/GInPipe#2]
Thank you so much for creating this tool! I've been looking through the paper and this repo and was wondering if you had any scripts for the simulation study available publicly somewhere? Specifically, I'm hoping to find code to recreate the data generation process. 

Thanks in advance!

**Comment by maureensmith** [comment]
The code for the simulations is available here: https://github.com/maureensmith/GInSim
Good point, will link it also to this repo. 
Will add some descriptions to the README, too. But in brief
- there is no extra environment for the simulation, but you can activate the conda environment for GInPipe 
- you'll find a prepared bash script to call the routines with different parameters: run_covid_evolution_with_shredding.sh
- to get the desciptions for the parameters you can call: generate_simulation_data.py --help
Hope that helps :)

**Comment by DOH-PNT0303** [comment]
Thank you so much @maureensmith!! I appreciate it :)
